const MOCK_MOVIES = [
  { id: 278,      title: "The Shawshank Redemption",                         genres: ["Drama","Crime"],                          year: 1994, poster: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",   rating: 8.7 },
  { id: 238,      title: "The Godfather",                                     genres: ["Drama","Crime"],                          year: 1972, poster: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",   rating: 8.7 },
  { id: 240,      title: "The Godfather Part II",                             genres: ["Drama","Crime"],                          year: 1974, poster: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",   rating: 8.6 },
  { id: 424,      title: "Schindler's List",                                  genres: ["Drama","History","War"],                  year: 1993, poster: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",   rating: 8.6 },
  { id: 155,      title: "The Dark Knight",                                   genres: ["Action","Crime","Thriller"],              year: 2008, poster: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",   rating: 8.5 },
  { id: 497,      title: "The Green Mile",                                    genres: ["Fantasy","Drama","Crime"],                year: 1999, poster: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",   rating: 8.5 },
  { id: 129,      title: "Spirited Away",                                     genres: ["Animation","Family","Fantasy"],           year: 2001, poster: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",   rating: 8.5 },
  { id: 19404,    title: "Dilwale Dulhania Le Jayenge",                       genres: ["Comedy","Drama","Romance"],               year: 1995, poster: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",   rating: 8.5 },
  { id: 122,      title: "The Lord of the Rings: The Return of the King",     genres: ["Adventure","Fantasy","Action"],           year: 2003, poster: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",   rating: 8.5 },
  { id: 680,      title: "Pulp Fiction",                                      genres: ["Thriller","Crime","Comedy"],              year: 1994, poster: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",   rating: 8.5 },
  { id: 372058,   title: "Your Name.",                                        genres: ["Animation","Romance","Drama"],            year: 2016, poster: "/q719jXXEzOoYaps6babgKnONONX.jpg",   rating: 8.5 },
  { id: 157336,   title: "Interstellar",                                      genres: ["Adventure","Drama","Science Fiction"],    year: 2014, poster: "/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",   rating: 8.5 },
  { id: 429,      title: "The Good, the Bad and the Ugly",                    genres: ["Western"],                                year: 1966, poster: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",   rating: 8.5 },
  { id: 13,       title: "Forrest Gump",                                      genres: ["Comedy","Drama","Romance"],               year: 1994, poster: "/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",   rating: 8.5 },
  { id: 769,      title: "GoodFellas",                                        genres: ["Drama","Crime"],                          year: 1990, poster: "/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg",   rating: 8.5 },
  { id: 346,      title: "Seven Samurai",                                     genres: ["Action","Drama"],                         year: 1954, poster: "/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg",   rating: 8.5 },
  { id: 550,      title: "Fight Club",                                        genres: ["Drama","Thriller"],                       year: 1999, poster: "/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg",   rating: 8.4 },
  { id: 637,      title: "Life Is Beautiful",                                 genres: ["Comedy","Drama"],                         year: 1997, poster: "/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg",   rating: 8.4 },
  { id: 120,      title: "The Lord of the Rings: The Fellowship of the Ring", genres: ["Adventure","Fantasy","Action"],           year: 2001, poster: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",   rating: 8.4 },
  { id: 598,      title: "City of God",                                       genres: ["Drama","Crime"],                          year: 2002, poster: "/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",   rating: 8.4 },
  { id: 11216,    title: "Cinema Paradiso",                                   genres: ["Drama","Romance"],                        year: 1988, poster: "/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg",   rating: 8.4 },
  { id: 121,      title: "The Lord of the Rings: The Two Towers",             genres: ["Adventure","Fantasy","Action"],           year: 2002, poster: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",   rating: 8.4 },
  { id: 539,      title: "Psycho",                                            genres: ["Horror","Thriller","Mystery"],            year: 1960, poster: "/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",   rating: 8.4 },
  { id: 510,      title: "One Flew Over the Cuckoo's Nest",                  genres: ["Drama"],                                  year: 1975, poster: "/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg",   rating: 8.4 },
  { id: 324857,   title: "Spider-Man: Into the Spider-Verse",                 genres: ["Animation","Action","Adventure"],         year: 2018, poster: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",   rating: 8.4 },
  { id: 378064,   title: "A Silent Voice: The Movie",                        genres: ["Animation","Drama","Romance"],            year: 2016, poster: "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",   rating: 8.4 },
  { id: 807,      title: "Se7en",                                             genres: ["Crime","Mystery","Thriller"],             year: 1995, poster: "/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",   rating: 8.4 },
  { id: 244786,   title: "Whiplash",                                          genres: ["Drama","Music","Thriller"],               year: 2014, poster: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",   rating: 8.4 },
  { id: 423,      title: "The Pianist",                                       genres: ["Drama","War"],                            year: 2002, poster: "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",   rating: 8.4 },
  { id: 27205,    title: "Inception",                                         genres: ["Action","Science Fiction","Adventure"],   year: 2010, poster: "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",   rating: 8.4 },
  { id: 567,      title: "Rear Window",                                       genres: ["Thriller","Mystery","Drama"],             year: 1954, poster: "/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",   rating: 8.3 },
  { id: 569094,   title: "Spider-Man: Across the Spider-Verse",               genres: ["Animation","Action","Adventure"],         year: 2023, poster: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",   rating: 8.3 },
  { id: 105,      title: "Back to the Future",                                genres: ["Adventure","Comedy","Science Fiction"],   year: 1985, poster: "/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg",   rating: 8.3 },
  { id: 128,      title: "Princess Mononoke",                                 genres: ["Adventure","Fantasy","Animation"],        year: 1997, poster: "/cMYCDADoLKLbB83g4WnJegaZimC.jpg",   rating: 8.3 },
  { id: 1184918,  title: "The Wild Robot",                                    genres: ["Family","Animation","Science Fiction"],   year: 2024, poster: "/eG9lz41mJqsI4J6ubMtVqD26q2J.jpg",   rating: 8.3 },
  { id: 3782,     title: "Ikiru",                                             genres: ["Drama"],                                  year: 1952, poster: "/dgNTS4EQDDVfkzJI5msKuHu2Ei3.jpg",   rating: 8.3 },
  { id: 10494,    title: "Perfect Blue",                                      genres: ["Animation","Thriller"],                   year: 1998, poster: "/6WTiOCfDPP8XV4jqfloiVWf7KHq.jpg",   rating: 8.3 },
  { id: 533514,   title: "Violet Evergarden: The Movie",                      genres: ["Animation","Drama","Fantasy"],            year: 2020, poster: "/bajajkoErDst0JxdFyBkABiF9rW.jpg",   rating: 8.3 },
  { id: 207,      title: "Dead Poets Society",                                genres: ["Drama"],                                  year: 1989, poster: "/erzbMlcNHOdx24AXOcn2ZKA7R1q.jpg",   rating: 8.3 },
  { id: 1585,     title: "It's a Wonderful Life",                             genres: ["Drama","Family","Fantasy"],               year: 1946, poster: "/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg",   rating: 8.3 },
  { id: 914,      title: "The Great Dictator",                                genres: ["Comedy","War"],                           year: 1940, poster: "/1QpO9wo7JWecZ4NiBuu625FiY1j.jpg",   rating: 8.3 },
  { id: 77338,    title: "The Intouchables",                                  genres: ["Drama","Comedy"],                         year: 2011, poster: "/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg",   rating: 8.3 },
  { id: 8587,     title: "The Lion King",                                     genres: ["Animation","Family","Drama"],             year: 1994, poster: "/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",   rating: 8.3 },
  { id: 603,      title: "The Matrix",                                        genres: ["Action","Science Fiction"],               year: 1999, poster: "/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg",   rating: 8.2 },
  { id: 670,      title: "Oldboy",                                            genres: ["Drama","Thriller","Mystery"],             year: 2003, poster: "/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",   rating: 8.2 },
  { id: 299534,   title: "Avengers: Endgame",                                 genres: ["Adventure","Science Fiction","Action"],   year: 2019, poster: "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",   rating: 8.2 },
  { id: 299536,   title: "Avengers: Infinity War",                            genres: ["Adventure","Action","Science Fiction"],   year: 2018, poster: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",   rating: 8.2 },
  { id: 620249,   title: "The Legend of Hei",                                 genres: ["Animation","Fantasy","Action"],           year: 2019, poster: "/4jfbKKLpqts3i2h2obkrONcjTg1.jpg",   rating: 8.3 },
  { id: 652837,   title: "Josee, the Tiger and the Fish",                     genres: ["Animation","Drama","Romance"],            year: 2020, poster: "/z1D8xi9x4uEhyFruo7uEHXUMD4K.jpg",   rating: 8.3 },
  { id: 311,      title: "Once Upon a Time in America",                       genres: ["Drama","Crime"],                          year: 1984, poster: "/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg",   rating: 8.4 },
  { id: 335,      title: "Once Upon a Time in the West",                      genres: ["Drama","Western"],                        year: 1968, poster: "/qbYgqOczabWNn2XKwgMtVrntD6P.jpg",   rating: 8.3 },
  { id: 14537,    title: "Harakiri",                                          genres: ["Action","Drama","History"],               year: 1962, poster: "/3nPwMd3KviJWaHzG9fZCqlwWMas.jpg",   rating: 8.4 },
  { id: 18491,    title: "Neon Genesis Evangelion: The End of Evangelion",    genres: ["Animation","Science Fiction","Drama"],    year: 1997, poster: "/j6G24dqI4WgUtChhWjfnI4lnmiK.jpg",   rating: 8.3 },
  { id: 599,      title: "Sunset Boulevard",                                  genres: ["Drama"],                                  year: 1950, poster: "/zt8aQ6ksqK6p1AopC5zVTDS9pKT.jpg",   rating: 8.3 },
  { id: 3082,     title: "Modern Times",                                      genres: ["Comedy","Drama","Romance"],               year: 1936, poster: "/7uoiKOEjxBBW0AgDGQWrlfGQ90w.jpg",   rating: 8.3 },
];
