name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
      - prepro

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "carbonecar@gmail.com"
          git config user.name "carbonecar"
          git push https://carbonecar:$HF_TOKEN@huggingface.co/spaces/carbonecar/recomendador-peliculas HEAD:main
